blog/urls.py
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name="blog"),
    path('<int:blog_id>', views.details, name="details"),
]

myprofiles/urls.py
from django.contrib import admin
from django.urls import include, path
from porfolio import views
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('blog/', include('blog.urls')),
    ]

    
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from datetime import datetime

class Blog(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField(max_length=500)
    date = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return self.title
    

porfolio/models.py
from django.db import models

class Project(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField(max_length=500)
    img=models.ImageField(upload_to='myprofiles/portfolio')
    url=models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

# Create your views here.
def blog(request):
    theblog=Blog.objects.all()
    return render(request,'blog/blog.html',{"blog":theblog})

def details(request,blog_id):
    blog=get_object_or_404(Blog, pk=blog_id)
    return render(request,'blog/details.html',{"blog":blog})

porfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    theproject=Project.objects.all()
    return render(request,"portfolio/home.html", {"project": theproject})

blog/templates/blog/blog.html
<h1>Blogs</h1>

<h1>Padmaja has written {{ blog.count}} blog{{blog.count|pluralize}}</h1>

{% for i in blog %}
<a href="{% url  'blog:details'  i.id %}"><h1>{{ i.title }}</h1></a>
<h2>{{ i.description|truncatechars:4 }}</h2>
<p>{{ i.date|date:'M d Y'|upper }}</p>

{% endfor %}

blog/templates/blog/details.html
<h1>{{ blog.title }}</h1>
<h2>{{ blog.date|date:'F jS Y'}}</h2>
<p>{{ blog.description|safe }}</p>

porfolio/templates/portfolio/home.html
<h1>Home</h1>

{% load static %}
<a href="{% url "blog:blog" %}">Blog</a>
<br>
<img src="{% static "porfolio/IMG_2291.JPG" %}" alt="My image" height=200 ,width=200>
{% for i in project %}
 <h2>{{ i.title }}</h2>   
 <p>{{ i.description|safe }}</p>
 <img src= "{{ i.img.url }}" height=300 width=300>
 {% if i.url %}
 <br>
 <a href="{{ i.url }}">link</a>
 {% endif %}
{% endfor %}